### ISSUE TITLE
Nested path expression in bool group ... fails with com.fasterxml.jackson.core.JsonGenerationException: Current context not an ARRAY but OBJECT

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-elastic#7]
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Current context not an ARRAY but OBJECT
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1649)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeEndArray(WriterBasedJsonGenerator.java:150)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.endBoolGroupList(ElasticDocQueryContext.java:326)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.endBool(ElasticDocQueryContext.java:344)
	at com.avaje.ebeaninternal.server.expression.DefaultExpressionList.writeDocQuery(DefaultExpressionList.java:154)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeFilter(ElasticDocQueryContext.java:135)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeElastic(ElasticDocQueryContext.java:113)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.asElasticQuery(ElasticDocQueryContext.java:92)

**Comment by rbygrave** [comment]
Test case:
```java
    Query<Order> query = server.find(Order.class)
        .setUseDocStore(true)
        .where()
        .eq("customer.id", 12323)
        .eq("details.product.sku","A100")
        .query();
```

So there is a Bool MUST group that wraps a normal and nested path expression and this fails.
